version: '3.7'

services:

    ollama:
      hostname: ollama
      image: ollama/ollama
      container_name: ollama
      ports:
        - "11434:11434"

    postgres:
      image: ankane/pgvector:v0.5.0
      container_name: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vector_store
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      healthcheck:
        test: "pg_isready -U postgres -d vector_store"
        interval: 2s
        timeout: 20s
        retries: 10


